### ISSUE TITLE
Getting errors on invalid redirect URI

### ISSUE THREAD

**Issue by jlei523** [Slotos/passport-reddit#16]
![image](https://user-images.githubusercontent.com/3815607/65339566-f16adf80-dbfe-11e9-82a5-f2f3ffa01aa7.png)
Any ideas?

**Comment by Slotos** [comment]
https://github.com/reddit-archive/reddit/wiki/OAuth2 demands you set your request `redirect_uri` exactly to the value you set in https://www.reddit.com/prefs/apps.

However, reddit OAuth implementation did have its quirks in the past. E.g. https://www.reddit.com/r/redditdev/comments/17ka6l/oauth_invalid_redirect_uri_parameter/c86hvnd/

Check whether your request is properly formed and keep in mind that `redirect_uri` might be a red herring.

**Comment by jlei523** [comment]
@Slotos Where can I pass `redirect_uri` into passport-reddit? The `passport-reddit` documentation doesn't mention anything about it.

**Comment by Slotos** [comment]
It's copied from `callbackURL` parameter in `passport-oauth2`, which this library is a wrapper around.

**Comment by jlei523** [comment]
@Slotos Thank you! It worked. I made a pull request to fix and clarify the example.
